### ISSUE TITLE
bug : answers right several times

### ISSUE THREAD

**Issue by mothsART** [uggla/rock_run#1]
When we try to response several time on the same answer, there is some bugs :

![Capture d’écran du 2024-11-02 21-40-52](https://github.com/user-attachments/assets/94a249f1-0a7d-46ed-8b76-b8dddc4be0a8)

![Capture d’écran du 2024-11-02 21-51-38](https://github.com/user-attachments/assets/dc8836d5-6e92-4f05-afbb-2f8e37fa302e)

**Comment by uggla** [comment]
Funny bug. Thanks for submitting it; I did not think about that. :+1:
